AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Lambda sencilla creada con CloudFormation para aprender
  Infrastructure as Code.

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Ambiente donde se desplegara la aplicacion.

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaToAssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: SendMessagesToSupportJobsQueue
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowSendingSupportJobs
                Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt SupportJobsQueue.Arn

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hello-lambda

  ApiLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - ApiLambdaLogGroup
    Properties:
      FunctionName: !Sub ai-customer-support-agent-${EnvironmentName}
      Description: Lambda creada completamente mediante CloudFormation.
      Runtime: python3.14
      Handler: functions.api.handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code: ../src/
      MemorySize: 128
      Timeout: 10

      Environment:
        Variables:
          APP_ENV: !Ref EnvironmentName
          SERVICE_NAME: ai-customer-support-agent
          LOG_LEVEL: INFO
          SUPPORT_JOBS_QUEUE_URL: !Ref SupportJobsQueue
          BEDROCK_MODEL_ID: amazon.nova-micro-v1:0

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hello-lambda

  ApiLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/ai-customer-support-agent-${EnvironmentName}
      RetentionInDays: 14


  SupportHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ai-customer-support-agent-api-${EnvironmentName}
      Description: HTTP API for the AI Customer Support Agent
      ProtocolType: HTTP
  
  ApiLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SupportHttpApi
      Description: Lambda proxy integration for the support API
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
        - FunctionArn: !GetAtt ApiLambdaFunction.Arn
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 10000

  HealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SupportHttpApi
      AuthorizationType: NONE
      RouteKey: GET /health
      Target: !Sub integrations/${ApiLambdaIntegration}

  ChatRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SupportHttpApi
      AuthorizationType: NONE
      RouteKey: POST /chat
      Target: !Sub integrations/${ApiLambdaIntegration}

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SupportHttpApi
      AuthorizationType: NONE
      RouteKey: $default
      Target: !Sub integrations/${ApiLambdaIntegration}

  ApiGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/ai-customer-support-agent-${EnvironmentName}
      RetentionInDays: 14

  ApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn:
      - ApiGatewayAccessLogGroup
    Properties:
      ApiId: !Ref SupportHttpApi
      StageName: $default
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt ApiGatewayAccessLogGroup.Arn
        Format: '{"request_id":"$context.requestId","method":"$context.httpMethod","route_key":"$context.routeKey","path":"$context.path","status":"$context.status","response_length":"$context.responseLength","response_latency":"$context.responseLatency","source_ip":"$context.identity.sourceIp"}'

  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*
        - ApiId: !Ref SupportHttpApi
  
  SupportJobsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ai-customer-support-jobs-dlq-${EnvironmentName}

  SupportJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ai-customer-support-jobs-${EnvironmentName}
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SupportJobsDeadLetterQueue.Arn
        maxReceiveCount: 5

  WorkerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaToAssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: ConsumeSupportJobsQueue
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowConsumingSupportJobs
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt SupportJobsQueue.Arn
        - PolicyName: CommunicationWithBedrock
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Sid: AllowBedrockInference
                Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub arn:${AWS::Partition}:bedrock:${AWS::Region}::foundation-model/amazon.nova-micro-v1:0

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: ai-customer-support-agent

  SupportJobsWorkerLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - WorkerLambdaLogGroup
    Properties:
      FunctionName: !Sub ai-customer-support-worker-${EnvironmentName}
      Description: Processes support jobs pulled from SQS.
      Runtime: python3.14
      Handler: functions.worker.handler.handler
      Role: !GetAtt WorkerLambdaExecutionRole.Arn
      Code: ../src/
      MemorySize: 128
      Timeout: 10

      Environment:
        Variables:
          APP_ENV: !Ref EnvironmentName
          SERVICE_NAME: ai-customer-support-worker
          LOG_LEVEL: INFO
          SUPPORT_JOBS_QUEUE_URL: !Ref SupportJobsQueue
          BEDROCK_MODEL_ID: amazon.nova-micro-v1:0

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: ai-customer-support-agent
  
  WorkerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/ai-customer-support-worker-${EnvironmentName}
      RetentionInDays: 14

  SupportJobsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt SupportJobsQueue.Arn
      FunctionName: !Ref SupportJobsWorkerLambdaFunction
      Enabled: true
      BatchSize: 5
      FunctionResponseTypes:
        - ReportBatchItemFailures
    

Outputs:
  LambdaFunctionName:
    Description: Nombre fisico de la funcion Lambda.
    Value: !Ref ApiLambdaFunction

  LambdaFunctionArn:
    Description: ARN de la funcion Lambda.
    Value: !GetAtt ApiLambdaFunction.Arn

  LambdaExecutionRoleName:
    Description: Nombre del execution role.
    Value: !Ref LambdaExecutionRole

  LambdaExecutionRoleArn:
    Description: ARN del execution role.
    Value: !GetAtt LambdaExecutionRole.Arn

  ApiId:
    Description: ID of the API Gateway HTTP API
    Value: !Ref SupportHttpApi

  ApiUrl:
    Description: Base URL of the API
    Value: !Sub https://${SupportHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}

  HealthUrl:
    Description: Health endpoint URL
    Value: !Sub https://${SupportHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/health

  ChatUrl:
    Description: Chat endpoint URL
    Value: !Sub https://${SupportHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/chat

  SupportJobsQueueUrl:
    Description: Main Queue URL
    Value: !Ref SupportJobsQueue

  SupportJobsQueueArn:
    Description: Main Queue ARN
    Value: !GetAtt SupportJobsQueue.Arn

  SupportJobsWorkerFunctionName:
    Description: Worker Lambda function name
    Value: !Ref SupportJobsWorkerLambdaFunction

  SupportJobsWorkerFunctionArn:
    Description: Worker Lambda function ARN
    Value: !GetAtt SupportJobsWorkerLambdaFunction.Arn

  SupportJobsWorkerExecutionRoleName:
    Description: Worker Lambda execution role name
    Value: !Ref WorkerLambdaExecutionRole

  SupportJobsWorkerExecutionRoleArn:
    Description: Worker Lambda execution role ARN
    Value: !GetAtt WorkerLambdaExecutionRole.Arn

  SupportJobsDeadLetterQueueUrl:
    Description: Dead queue URL
    Value: !Ref SupportJobsDeadLetterQueue

  SupportJobsDeadLetterQueueArn:
    Description: Dead queue ARN
    Value: !GetAtt SupportJobsDeadLetterQueue.Arn

  
